---
layout: post
title:  "Intentionally Ringing in the New Year"
date:   "2026-01-11"
categories: [personal, self-improvement]
---

Many blog-post bits are spilled annually in retrospectives or plans for the coming year. Change this, lose that, etc. I've always found it hard to start a new habit in January-a bleak month in its own right-and I'm supposed to deny stuff that, until then, are comforting vices? No thanks; let's break our habits in the shortest month of the year, thank you.

> Complete aside: I make my return to work in January go smoother by opening a panettone I purchased in December on the first day back. I call it Janettone, and it's a habit I would like to share with the world. This year's is a limoncello one, and it's a lovely way to start a workday.

This year, I'm looking to take something I've tried to apply for several months a bit further. I want to be more intentional about everything I do. Phone down more. Single-screening, not multi-screening. Being intentional about my actions doesn't preclude me simply wanting to enjoy what I do.

I want to be more present in my forties, and that's what I intend to do.`